### PR TITLE
Use same hasher for LogClient and trillian-log

### LINKED ISSUE #688: Investigate CreateEpoch failed: sths.Write(_, 1): WaitForInclusion(): signature is nil
Running the system with docker-compose (locally) with the current master yields the following output for the kt-signer:

```
I0707 10:48:00.422786       7 main.go:154] Signer starting
I0707 10:48:00.424914       7 signer.go:236] CreateEpoch: starting sequencing run
I0707 10:48:00.426203       7 signer.go:247] CreateEpoch: Previous SignedMapRoot: {Revision: 0, HighestFullyCompletedSeq: 0}
I0707 10:48:00.426759       7 signer.go:268] CreateEpoch: len(mutations): 0, len(indexes): 0
I0707 10:48:00.428843       7 signer.go:278] CreateEpoch: len(GetLeaves.MapLeafInclusions): 0
I0707 10:48:00.428855       7 signer.go:294] CreateEpoch: applied 0 mutations to 0 leaves
I0707 10:48:00.435733       7 signer.go:310] CreateEpoch: SetLeaves:{Revision: 1, HighestFullyCompletedSeq: 0}
E0707 10:48:00.442191       7 signer.go:129] CreateEpoch failed: sths.Write(2155217215888087658, 1): WaitForInclusion(): signature is nil
I0707 10:48:05.425090       7 signer.go:236] CreateEpoch: starting sequencing run
I0707 10:48:05.429200       7 signer.go:247] CreateEpoch: Previous SignedMapRoot: {Revision: 1, HighestFullyCompletedSeq: 0}
I0707 10:48:05.430332       7 signer.go:258] CreateEpoch: No mutations found. Exiting.
```
I thought this was resolved with #651. Querying the HTTP frontend it looks like the signer did its job, though. 
Investigate if this is still an issue or the output `WaitForInclusion(): signature is nil` is just a bit confusing. This might be a trillian issue (in `LogClient.AddLeaf`).

### PR DESCRIPTION
**Pull request by Liamsi**
We currently create the tree using [log_payload.json](https://github.com/google/keytransparency/blob/a7b3f6246ec0be578713fca451afe260dce45317/scripts/log_payload.json#L8) which uses SHA256 as a hasher. The log-client created by the kt-signer used `OBJECT_RFC6962_SHA256`. A following PR should make this a param to `config.LogClient` and autom. read it (either from the json or from a cmd-flag/config flag).

Fixes `WaitForInclusion` timing out.

Together with google/trillian#729 this resolves #688

### CODE REVIEW

File: cmd/keytransparency-signer/main.go [hunk 1]
```diff
@@ -63,6 +63,8 @@ var (
 	logID     = flag.Int64("log-id", 0, "Trillian Log ID")
 	logURL    = flag.String("log-url", "", "URL of Trillian Log Server for Signed Map Heads")
 	logPubKey = flag.String("log-key", "", "File path to public key of the Trillian Log")
+	// TODO(ismail): add hasher flag; defaults to hasher used to create tree in
```
Comment (gdbelvin) [inline cmd/keytransparency-signer/main.go]: no flag needed

File: impl/config/config.go [hunk 2]
```diff
@@ -21,13 +21,13 @@ import (
 	"github.com/google/trillian"
 	"github.com/google/trillian/client"
 	"github.com/google/trillian/crypto/keys"
-	"github.com/google/trillian/merkle/hashers"
```
Comment (gdbelvin) [inline impl/config/config.go]: keep this as the object hasher, change the create tree command

**Comment by Liamsi** [comment]
done
