### PR TITLE
Monitor verification logic

### LINKED ISSUE #800: Mutator returns inclusion proof in wrong epoch
The mutator should return inclusion proofs (for mutations) in the previous epoch. Currently, it returns inclusion proofs in the requested epoch:
The relevant parts are these lines in [mutation.go](https://github.com/google/keytransparency/blob/5a30e36835b6a41fb6e1e20e2e8cd30dc9a54442/core/mutation/mutation.go#L109-L120):

https://github.com/google/keytransparency/blob/5a30e36835b6a41fb6e1e20e2e8cd30dc9a54442/core/mutation/mutation.go#L109-L120

(should be `s.inclusionProofs(ctx, indexes, in.Epoch-1) `

### PR DESCRIPTION
**Pull request by Liamsi**
This PR contains the monitor verification logic which should be plugged into the monitor after #776  is merged.

Includes a fix for https://github.com/google/keytransparency/issues/800 and related to this a temporary workaround for #811. 

resolves #800

### CODE REVIEW

File: core/monitor/verify.go [hunk 1]
```diff
@@ -18,14 +18,191 @@
 package monitor
 
 import (
+	"bytes"
+	"encoding/json"
+	"errors"
+	"math/big"
+
+	"github.com/golang/glog"
+
```
Comment (cesarghali) [inline core/monitor/verify.go]: Please remove empty line.

File: core/monitor/verify.go [hunk 2]
```diff
@@ -18,14 +18,191 @@
...
+	"github.com/google/trillian/merkle"
+	"github.com/google/trillian/storage"
+
```
Comment (cesarghali) [inline core/monitor/verify.go]: Please remove empty line.

File: core/monitor/verify.go [hunk 3]
```diff
@@ -18,14 +18,191 @@
...
+	tcrypto "github.com/google/trillian/crypto"
+
+	"github.com/google/keytransparency/core/mutator/entry"
```
Comment (cesarghali) [inline core/monitor/verify.go]: Move this to the second section of the imports:

* Standard packages.
* KT packages.
* Others.
* Protos.
