### PR TITLE
Prometheus

### LINKED ISSUE #610: server panics when requested by HTTP before tree creation
I encountered this while working on kubernetes/gcloud deployment but it should be independent from that. When one starts the key-server (and everything else needed, like db, trillian-map, etc) before creating a tree (to get a map-/log-id) the server panics when querying it by
`curl -k https://localhost:8080/v1/users/foo@bar.com` 

Opening this issue so that this doesn't get lost. Will investigate later.

<details>
<summary>Click to see the kt-server log output immediately after sending above GET request:</summary>
<pre><code>
2017-06-14T20:12:39.056644225Z I0614 20:12:39.055952       6 frontend.go:248] Listening on 0.0.0.0:8080
2017-06-14T20:21:30.730198703Z I0614 20:21:30.729792       6 frontend.go:142] 1>{
2017-06-14T20:21:30.730242755Z   "user_id": "foo@bar.com"
2017-06-14T20:21:30.730249946Z }
2017-06-14T20:21:30.745284123Z E0614 20:21:30.745171       6 keyserver.go:99] GetLeaves(): rpc error: code = NotFound desc = sql: no rows in result set
2017-06-14T20:21:30.747846122Z panic: reflect: call of reflect.Value.NumField on zero Value
2017-06-14T20:21:30.747860852Z 
2017-06-14T20:21:30.747865978Z goroutine 45 [running]:
2017-06-14T20:21:30.747871415Z reflect.flag.mustBe(0x0, 0x19)
2017-06-14T20:21:30.747876325Z 	/usr/local/go/src/reflect/value.go:201 +0xae
2017-06-14T20:21:30.747880673Z reflect.Value.NumField(0x0, 0x0, 0x0, 0x0)
2017-06-14T20:21:30.747883935Z 	/usr/local/go/src/reflect/value.go:1170 +0x34
2017-06-14T20:21:30.747887786Z github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0xd12480, 0xc4200fb790, 0xcdc080, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200fb7b0, 0x410d58)
2017-06-14T20:21:30.747893523Z 	/go/src/github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb/jsonpb.go:176 +0x171
2017-06-14T20:21:30.747897428Z github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0xd12480, 0xcd4100, 0xc4202f0380, 0xcdc080, 0x0, 0x9dca20, 0xcd5701)
2017-06-14T20:21:30.74790097Z 	/go/src/github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb/jsonpb.go:80 +0xca
2017-06-14T20:21:30.747904759Z github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb.(*Marshaler).MarshalToString(0xd12480, 0xcdc080, 0x0, 0xcdc080, 0x0, 0x1, 0xcd5780)
2017-06-14T20:21:30.74790839Z 	/go/src/github.com/google/keytransparency/vendor/github.com/golang/protobuf/jsonpb/jsonpb.go:86 +0x6e
2017-06-14T20:21:30.747912143Z main.jsonLogger(0x7f816d0ff280, 0xc4202daff0, 0x9c3100, 0xc420185530, 0xc42017d9a0, 0xc42017d9c0, 0x0, 0xc4203559b8, 0x410d58, 0x50)
2017-06-14T20:21:30.747915645Z 	/go/src/github.com/google/keytransparency/cmd/keytransparency-server/frontend.go:152 +0x35b
2017-06-14T20:21:30.747925103Z github.com/google/keytransparency/impl/proto/keytransparency_v1_service._KeyTransparencyService_GetEntry_Handler(0x9a34e0, 0xc4202481b0, 0x7f816d0ff280, 0xc4202daff0, 0xc42018b040, 0xa41fb8, 0x0, 0x0, 0x0, 0x0)
2017-06-14T20:21:30.747929369Z 	/go/src/github.com/google/keytransparency/impl/proto/keytransparency_v1_service/keytransparency_v1_service.pb.go:143 +0x177
2017-06-14T20:21:30.747932779Z github.com/google/keytransparency/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420260000, 0xce1960, 0xc4202d6cc0, 0xc4202e2a00, 0xc420184660, 0xd16c00, 0x0, 0x0, 0x0)
2017-06-14T20:21:30.747939376Z 	/go/src/github.com/google/keytransparency/vendor/google.golang.org/grpc/server.go:771 +0xc84
2017-06-14T20:21:30.747942793Z github.com/google/keytransparency/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420260000, 0xce1960, 0xc4202d6cc0, 0xc4202e2a00, 0x0)
2017-06-14T20:21:30.747983946Z 	/go/src/github.com/google/keytransparency/vendor/google.golang.org/grpc/server.go:971 +0x15a0
2017-06-14T20:21:30.747989883Z github.com/google/keytransparency/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202d2b60, 0xc420260000, 0xce1960, 0xc4202d6cc0, 0xc4202e2a00)
2017-06-14T20:21:30.747993258Z 	/go/src/github.com/google/keytransparency/vendor/google.golang.org/grpc/server.go:537 +0xa9
2017-06-14T20:21:30.74800128Z created by github.com/google/keytransparency/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2017-06-14T20:21:30.74800467Z 	/go/src/github.com/google/keytransparency/vendor/google.golang.org/grpc/server.go:538 +0xa1

</pre></code>
</details>

### PR DESCRIPTION
**Pull request by gdbelvin**
Merge #578 first.

Adds prometheus monitoring
- grpc statistics
- signer statistics 
- prometheus configuration

Fixes #610

### CODE REVIEW

File: cmd/keytransparency-server/main.go [hunk 1]
```diff
@@ -122,43 +123,6 @@ func grpcHandlerFunc(grpcServer *grpc.Server, otherHandler http.Handler) http.Ha
...
-	s, err = marshaler.MarshalToString(pb)
-	if err != nil {
-		glog.Warningf("Failed to marshal %v", pb)
-		return resp, err
-	}
-	glog.Infof("%v<%v", requestCounter, s)
-
-	return resp, err
-}
-
```
Comment (Liamsi) [inline cmd/keytransparency-server/main.go]: These changes will also resolve #610 :+1:

File: core/signer/signer.go [hunk 2]
```diff
@@ -257,21 +289,32 @@ func (s *Signer) CreateEpoch(ctx context.Context, forceNewEpoch bool) error {
...
 	})
+	mapSetEnd := time.Now()
 	if err != nil {
 		return err
 	}
 	glog.V(2).Infof("CreateEpoch: SetLeaves.HighestFullyCompletedSeq: %v", seq)
 
 	// Put SignedMapHead in an append only log.
-	if err := s.sths.Write(ctx, s.logID, setResp.MapRoot.MapRevision, setResp.MapRoot); err != nil {
+	// TODO: sths.Write currently hangs.
```
Comment (Liamsi) [inline core/signer/signer.go]: `// TODO: sths.Write currently hangs.`
Is this still true? If yes, change to TODO(name):

File: docker-compose.yml [hunk 3]
```diff
@@ -1,5 +1,15 @@
 version: "3"
 services:
+  prometheus:
+    depends_on:
+      - kt-server
+      - kt-signer
+    image: prom/prometheus
+    volumes: 
+      - ./prometheus.yml:/etc/prometheus/prometheus.yml
+      - ./prometheus.rules:/etc/prometheus/prometheus.rules
```
Comment (Liamsi) [inline docker-compose.yml]: Can't we just `ADD`/`COPY` these files in a seperate Dockerfile? This will save us some struggle when running this from kubernetes/gce.

File: core/signer/signer.go [hunk 4]
```diff
@@ -25,12 +26,42 @@ import (
...
 	"github.com/google/trillian"
+	"github.com/prometheus/client_golang/prometheus"
 	"golang.org/x/net/context"
 
 	tpb "github.com/google/keytransparency/core/proto/keytransparency_v1_types"
 	"github.com/google/trillian/util"
 )
 
+var (
+	timeout      = 10 * time.Second
```
Comment (Liamsi) [inline core/signer/signer.go]: Should this timeout be a commandline flag? Are 10s always a reasonable timeout?

File: docker-compose.yml [hunk 5]
```diff
@@ -134,9 +147,8 @@ services:
       VRF_PUB: /kt/genfiles/vrf-pubkey.pem
       SIGN_KEY: /trillian/log-rpc-server.privkey.pem
       SIGN_KEY_PW: towel
+      SIGN_PERIOD: 5s
```
Comment (Liamsi) [inline docker-compose.yml]: The corresponding flag got renamed to `--min-period` for the signer. I would suggest to name this `MIN_SIGN_PERIOD` (Already fixed in #607: https://github.com/Liamsi/keytransparency/blob/6d3dde3ce28615df44bb80ac2076307c6e572362/cmd/keytransparency-signer/Dockerfile#L26). 
If this gets merged before #607, please update the flag in the Dockerfile (otherwise docker-compose won't succeed starting the kt-signer).

File: core/signer/signer.go (hunk 2 above)
Comment (gdbelvin) [inline core/signer/signer.go]: done

File: core/signer/signer.go (hunk 4 above)
Comment (gdbelvin) [inline core/signer/signer.go]: removed and replaced with `minInterval`

File: docker-compose.yml (hunk 3 above)
Comment (gdbelvin) [inline docker-compose.yml]: done

File: docker-compose.yml (hunk 5 above)
Comment (gdbelvin) [inline docker-compose.yml]: done

**Comment by gdbelvin** [comment]
Updated PTAL

**Comment by Liamsi** [comment]
Thanks! LGTM
