### PR TITLE
Fix DB locked flakiness in tests

### LINKED ISSUE #531: Test flakiness: db is locked
I suspect there's a missing txn.Commit or txn.Rollback somewhere.

### PR DESCRIPTION
**Pull request by gdbelvin**
Some integration tests make GET requests while new epochs are being created in the background, using the same *sql.DB connection, producing a transient "database is locked" error. 

Background: 
- Reading while a write is occurring requires multiple *sql.DB connections to the same db. 
- In-memory tests only allow one *sql.DB connection to the test database.
- *sql.DB is [not threadsafe](https://github.com/mattn/go-sqlite3#faq) for write/reads on multiple goroutines.

Solution: 
Synchronize access to sql.DB by waiting for epoch creation to finish before making GET requests.  
It adds a channel for new epoch notifications which allows tests to wait for new epochs before advancing to the next steps in the test. 

This PR resolves this issue by
- Converting all `sqlhist` operations to consistently take Transactions as input. 
  - `Commit` now takes a txn
  - `Epoch` now takes a txn
  - `Commit` and `QueueLeaf` no longer return the current epoch as a return value since it's accuracy is not guaranteed outside of a transaction. 
- Ensuring that `txn.Rollback()` is called on all error paths. 
- `Queue` publishes a channel of events for new epoch creation.
- Tests use `Queue.AdvanceEpoch()` rather than performing the epoch itself. 

Fixes #531

### CODE REVIEW

File: core/mapserver/mapserver.go [hunk 1]
```diff
@@ -70,12 +70,19 @@ func (m *mapServer) signRoot(ctx context.Context) (*trillian.SignedMapRoot, erro
...
+		if retErr != nil {
+			if rbErr := txn.Rollback(); rbErr != nil {
+				retErr = fmt.Errorf("%v, Rollback(): %v", retErr, rbErr)
+			}
+		}
+	}()
 	root, err := m.tree.ReadRootAt(txn, epoch)
 	if err != nil {
-		return nil, fmt.Errorf("ReadRootAt err: %v", err)
+		return nil, fmt.Errorf("ReadRootAt(%v): %v", epoch, err)
```
Comment (cesarghali) [inline core/mapserver/mapserver.go]: nit: what do you think about changing the error text to `ReadRootAt(%v) failed: %v`. I find it helpful to search long logs for the words "fail", or "error" when something goes wrong.

File: core/signer/signer.go [hunk 2]
```diff
@@ -125,13 +129,16 @@ func (s *Signer) ProcessMutation(ctx context.Context, txn transaction.Txn, index
...
 // CreateEpoch signs the current map head.
 func (s *Signer) CreateEpoch(ctx context.Context, txn transaction.Txn) error {
-	epoch, err := s.tree.Commit(ctx)
+	if err := s.tree.Commit(txn); err != nil {
+		return fmt.Errorf("Commit(): %v", err)
+	}
+	epoch, err := s.tree.Epoch(txn)
 	if err != nil {
-		return fmt.Errorf("Commit err: %v", err)
+		return fmt.Errorf("Epoch(): %v", err)
```
Comment (cesarghali) [inline core/signer/signer.go]: Similar nit here.

File: core/signer/signer.go [hunk 3]
```diff
@@ -125,13 +129,16 @@ func (s *Signer) ProcessMutation(ctx context.Context, txn transaction.Txn, index
...
 	}
 	root, err := s.tree.ReadRootAt(txn, epoch)
 	if err != nil {
-		return fmt.Errorf("ReadRootAt err: %v", err)
+		return fmt.Errorf("ReadRootAt(%v): %v", epoch, err)
```
Comment (cesarghali) [inline core/signer/signer.go]: And here.

File: core/tree/tree.go [hunk 4]
```diff
@@ -15,26 +15,22 @@
...
-	"golang.org/x/net/context"
-
-	"github.com/google/keytransparency/core/transaction"
-)
+import "github.com/google/keytransparency/core/transaction"
 
 // Sparse is a temporal sparse merkle tree.
 type Sparse interface {
 	// QueueLeaf queues a leaf to be written on the next Commit(). QueueLeaf
 	// returns the epoch at which the leaf is queued.
```
Comment (cesarghali) [inline core/tree/tree.go]: Can you please fix the comment to match the new API?

File: impl/etcd/queue/etcd.go [hunk 5]
```diff
@@ -127,7 +136,7 @@ func (q *Queue) loop(ctx context.Context, wc v3.WatchChan, cbs callbacks) {
 	for resp := range wc {
 		for _, ev := range resp.Events {
 			if err := q.dequeue(ev.Kv.Key, ev.Kv.Value, ev.Kv.ModRevision, cbs); err != nil {
-				log.Printf(err.Error())
+				log.Printf("Error: dequeue(): %v", err)
```
Comment (cesarghali) [inline impl/etcd/queue/etcd.go]: :+1:

File: impl/sql/sqlhist/sqlhist.go [hunk 6]
```diff
@@ -93,76 +93,87 @@ const (
...
-		mapID:   mapID,
-		db:      db,
-		factory: factory,
-	}
-	if err := m.create(); err != nil {
-		return nil, err
-	}
-	if err := m.insertMapRow(); err != nil {
-		return nil, err
+func New(ctx context.Context, db *sql.DB, mapID int64, factory transaction.Factory) (m *Map, returnErr error) {
```
Comment (cesarghali) [inline impl/sql/sqlhist/sqlhist.go]: Please remove `db` as an argument since it's not used.

File: impl/sql/sqlhist/sqlhist.go [hunk 7]
```diff
@@ -93,76 +93,87 @@ const (
...
+		return -1, fmt.Errorf("Error reading epoch: %v", err)
+	}
+	if !epoch.Valid {
+		return -1, errInvalidEpoch
+	}
+	return epoch.Int64, nil
 }
 
 // QueueLeaf should only be called by the sequencer. If txn is nil, the operation
 // will not run in a transaction. QueueLeaf returns the epoch at which the leaf
```
Comment (cesarghali) [inline impl/sql/sqlhist/sqlhist.go]: Please update the comment.

File: impl/transaction/txn.go [hunk 8]
```diff
@@ -121,24 +120,20 @@ func (t *txn) Commit() error {
...
+				err = fmt.Errorf("%v, Rollback(): %v", err, rbErr)
 			}
 			return err
 		}
 	}
 
 	// Commit the database transaction. On failure, we lose the mutation.
 	if err := t.dbTxn.Commit(); err != nil {
-		return fmt.Errorf("database commit failed: %v", err)
+		return fmt.Errorf("db.Commit(): %v", err)
```
Comment (cesarghali) [inline impl/transaction/txn.go]: Similar nit here.

File: core/mapserver/mapserver.go (hunk 1 above)
Comment (gdbelvin) [inline core/mapserver/mapserver.go]: I prefer shorter error messages because they all get chained together:
`Dequeue(): CreateEpoch(): Commit(): table locked: SMH`
Seems cleaner than
`Dequeue() failed: CreateEpoch() failed: Commit() failed: table locked: SMH`
What do you think?

File: core/tree/tree.go (hunk 4 above)
Comment (gdbelvin) [inline core/tree/tree.go]: done

File: core/signer/signer.go (hunk 3 above)
Comment (gdbelvin) [inline core/signer/signer.go]: same

File: impl/sql/sqlhist/sqlhist.go (hunk 6 above)
Comment (gdbelvin) [inline impl/sql/sqlhist/sqlhist.go]: done

File: impl/sql/sqlhist/sqlhist.go (hunk 7 above)
Comment (gdbelvin) [inline impl/sql/sqlhist/sqlhist.go]: done

File: impl/transaction/txn.go (hunk 8 above)
Comment (gdbelvin) [inline impl/transaction/txn.go]: same as above

Comment (gdbelvin) [inline impl/transaction/txn.go]: same as above
