### PR TITLE
Split Mutation Verification Function

### LINKED ISSUE #1177: Split Verification Function
Verifying the legitimacy of a mutation can be broken into two parts:
1. Verifying that it is well formed without knowing what the current map value is.  This verification should be checked by the `keyserver`. 

2. Verifying that any references to the `current` value in the map are correct. Both the first check and this check should be run in the `sequencer`.

### PR DESCRIPTION
**Pull request by gdbelvin**
@Zyqsempai I've built on your PR a bit. (See #10968b4) I didn't want to presume to push to your branch, so I've opened a new one. Does this look reasonable? 

This PR splits the mutation function into two components:
1. `IsValidEntry` verifies the internal correctness of a mutation on it's own. 
2. `MutateFn` verifies pairs of entries and uses `IsValidEntry` as a helper. 

`IsValidEntry` also imposes the *new* requirement that every mutation be signed by one of the authorized keys in that same mutation. 

The Keyserver frontend will only check internal correctness on incoming mutations.  It doesn't make sense to do a full check at the keyserver because the ordering of mutations at that point has not been determined. 

The Sequencer will both check internal consistency and pairwise correctness in order to compute the next value for a user. 

Fixes #1177

### CODE REVIEW

File: core/mutator/entry/mutator_test.go [hunk 1]
```diff
@@ -177,7 +177,7 @@ func TestCheckMutation(t *testing.T) {
 			continue
 		}
 
-		if _, got := MutateFn(tc.old, m); got != tc.err {
+		if _, got := MutateFn(tc.old, m, true); got != tc.err {
```
Comment (golangcibot) [inline core/mutator/entry/mutator_test.go]: too many arguments (from `typecheck`)

File: core/mutator/entry/mutation_test.go [hunk 2]
```diff
@@ -114,7 +114,7 @@ func TestCreateAndVerify(t *testing.T) {
 			if err != nil {
 				t.Fatalf("FromLeafValue(%v): %v", tc.old, err)
 			}
-			newSignedEntry, err := MutateFn(oldSignedEntry, update.GetMutation())
+			newSignedEntry, err := MutateFn(oldSignedEntry, update.GetMutation(), true)
```
Comment (Zyqsempai) [inline core/mutator/entry/mutation_test.go]: Don't forget to remove unused param here.

**Comment by Zyqsempai** [comment]
@gdbelvin I like your version more then mine;) So, no worries.

**Comment by gdbelvin** [comment]
Marking `cla: yes` with @Zyqsempai 's permission to merge with their commit.

**Comment by Zyqsempai** [comment]
@gdbelvin What should i do to make googlebot stop complaining about my commit?;)
